export const ADD_TO_CART_LIST = 'ADD_TO_CART_LIST';
export const REMOVE_FROM_CART_LIST = 'REMOVE_FROM_CART_LIST';
export const LOAD_SHOP_LIST = 'LOAD_SHOP_LIST';
export const REMOVE_FROM_SHOT_LIST = 'REMOVE_FROM_SHOT_LIST';
export const ADD_TO_SHOP_LIST = 'ADD_TO_SHOP_LIST';
